//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hastane
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hasta
    {
        public int HastaID { get; set; }
        public string Tc { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string DogumTarihi { get; set; }
        public Nullable<bool> Cinsiyet { get; set; }
        public string Parola { get; set; }
        public string OlusturulmaTarihi { get; set; }
        public Nullable<bool> AktifMi { get; set; }
    }
}
