//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hastane
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ilac
    {
        public int IlacID { get; set; }
        public string Ad { get; set; }
        public Nullable<System.DateTime> OlusturulmaTarihi { get; set; }
        public Nullable<bool> AktifMi { get; set; }
    }
}
