//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hastane
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HastaneDBEntities1 : DbContext
    {
        public HastaneDBEntities1()
            : base("name=HastaneDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Hasta> Hastas { get; set; }
        public virtual DbSet<Ilac> Ilacs { get; set; }
        public virtual DbSet<Personel> Personels { get; set; }
        public virtual DbSet<PersonelIzin> PersonelIzins { get; set; }
        public virtual DbSet<PersonelTur> PersonelTurs { get; set; }
        public virtual DbSet<Randevu> Randevus { get; set; }
        public virtual DbSet<Recete> Recetes { get; set; }
        public virtual DbSet<ReceteIlac> ReceteIlacs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Brans> Brans1 { get; set; }
    }
}
