//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hastane
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recete
    {
        public int ReceteID { get; set; }
        public Nullable<int> HastaID { get; set; }
        public Nullable<int> PersonelID { get; set; }
        public Nullable<System.DateTime> RandevuSaati { get; set; }
        public Nullable<System.DateTime> OlusturulmaTarihi { get; set; }
        public Nullable<bool> ReceteOnay { get; set; }
    }
}
