//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hastane
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceteIlac
    {
        public int id { get; set; }
        public Nullable<int> ReceteID { get; set; }
        public Nullable<int> IlacID { get; set; }
    }
}
